(ns adventofcode.2018.day2)


(defn f1 [ids]
  (->> ids
    (map #(-> % frequencies vals set))
    (reduce
      (fn [[a b] counts]
        [(if (contains? counts 2) (inc a) a)
         (if (contains? counts 3) (inc b) b)])
      [0 0])
    (apply *)))

(assert (= 12 (f1 ["abcdef" "bababc" "abbcde" "abcccd" "aabcdd" "abcdee" "ababab"])))


(defn too-different? [a b]
  (->> b
    (map not= a)
    (filter true?)
    (count)
    (< 1)))


(defn common [a b]
  (->>
    (map vector a b)
    (filter (partial apply =))
    (map first)
    (apply str)))


(defn f2 [ids]
  (loop [ids ids]
    (let [[id1 & todo] ids
          partner #(when-not (too-different? id1 %) %)]
      (when (some? todo)
        (if-let [id2 (some partner todo)]
          (common id1 id2)
          (recur todo))))))






(assert (= "fgij" (f2 ["fghij" "wvxyz" "abcde" "klmno" "pqrst" "axcye"
                       "fguij"])))

(def input
  ["uqyoeiznvmzrstpkgnsacjxwld"
   "uqloeizfvmbrstpkgndacjxwyd"
   "dqgoeizfbmbrstpkgnhacjxwld"
   "uqyjeizfvmbrstpygntacjxwld"
   "uqyoeizfhmbrstppbnhacjxwld"
   "uqyoeizfvmbrstpkschanjxwld"
   "uqyoeizfvtbrstpkgnmazjxwld"
   "uqyoeizfvmyrstpzgnhacjxsld"
   "udtoeizfvmbrttpkgnhacjxwld"
   "uqyneizfvmbratpognhacjxwld"
   "uqyoeizfvmbrstpkunhaajxnld"
   "uqyteizfvmbrstpkgnhzcnxwld"
   "hqyteuzfvmbrstpkgnhacjxwld"
   "uqyoeizyvmbrsdpkgnhacdxwld"
   "uqyoeizfibbrsepkgnhacjxwld"
   "uqxoeizfvmbrstpkgnhaxjjwld"
   "iqaoeizfvmbrstpkrnhacjxwld"
   "uqyoeizpvvbrstpkghhacjxwld"
   "aqyoeizfvmbrstpbgnhfcjxwld"
   "uqyonfzfvmbrstpkgnhacjgwld"
   "uqyoeizovmhrstpkgnhacjxwvd"
   "uqyoegzfvmbrstpkgnfacjxrld"
   "uqyoeizfvmbrstpjgnwacjxwdd"
   "uqyogiifumbrstpkgnhacjxwld"
   "uqyorizfvmbrstpkgnhaezxwld"
   "uqyoexdfvmbretpkgnhacjxwld"
   "uqyoeizfvmbrstpkgwhlcjxzld"
   "uqyoeibfvmbrstpggnhzcjxwld"
   "udyoeizfvmbrstppwnhacjxwld"
   "ufyoeizfvmhrstpkgnfacjxwld"
   "aqyoeftfvmbrstpkgnhacjxwld"
   "uhyoeivfvmbrstpkgnhadjxwld"
   "uqyoeizfvmbrstpkgmhacjxhud"
   "uqyfeizfvmbrstpkgnhkljxwld"
   "uqyoeibfvmbrstpkgbhazjxwld"
   "uqyceizfvnbrslpkgnhacjxwld"
   "uqyoeizfvmirstpkonhacaxwld"
   "fqyooizfvmbrstpkgnhacjxwlq"
   "uqydeizfvmbgstpugnhacjxwld"
   "uqyoiizfvmbrstpkgnhacjalld"
   "uqyivizfvmbrstpkgnhocjxwld"
   "uqyoeizfvmbrstpngnhjcjxwtd"
   "uqyoeizfvmbrstpkynhrcexwld"
   "ugmfeizfvmbrstpkgnhacjxwld"
   "uqyoeizrvmbrstpkwnhycjxwld"
   "uqyoeiyfvmbrstpkgnlacjxwwd"
   "unyoeizfvmbrstrkgnhadjxwld"
   "uqyoeizhvmbrstpkgnhacjawlz"
   "uqyoeazfvmbrstpwgnhacjxwlp"
   "uqyoeiznvmbastpkgnhaccxwld"
   "kqyoeisfvmbrstikgnhacjxwld"
   "uqyoeizfvlxrstpmgnhacjxwld"
   "uqyoeiofvmbrstpkgniacjxwll"
   "uqyoeizfvmbrswpegnhacixwld"
   "uqyoeizfvmarstlkgnhanjxwld"
   "uuyoeizfvmbrstykgnhacjxwbd"
   "uqyoeizfvmbpstxkgnhacjxwlu"
   "uqyoqizfvmbrsspkgnhacjpwld"
   "uqyoeizfvmzrstnkgnhacjgwld"
   "uqyoeizfvmbrstrcgnhacjxwud"
   "uqyoeizfvmbrstpkgnuacxxwsd"
   "cqyoeizfvmbrscpkgnhacjxwpd"
   "sqyoeizfaobrstpkgnhacjxwld"
   "uqyoeizfvmbrgtpkgnhacjxbwd"
   "uqyoeibhvmbrstpkgnhagjxwld"
   "uqyoeizfvcbrstpkgzhactxwld"
   "uqkoeizfvmbrstijgnhacjxwld"
   "uqroelzfvmbrstpkgmhacjxwld"
   "uqyoeizfvmbrsfpcgnhkcjxwld"
   "uqyoeizfumgrstpygnhacjxwld"
   "uqyozibfvmbrstpkgnhacjwwld"
   "uqyoeigfvmbrstpkgjharjxwld"
   "uqpoeizfvmbrstpkgnhacjxrcd"
   "uqyoeizfvmbrskokgnhqcjxwld"
   "uqyoeikfvmbrstpkgehacjxwle"
   "uqygeizfvhbrstpkgnqacjxwld"
   "lqyoeizfvmbrsvpkgnhacjuwld"
   "uqyjeizfvmbectpkgnhacjxwld"
   "unyoeizfvmbrstpkgnhzckxwld"
   "uqyoeizfvmbrstpkgmoacjxwlm"
   "uqfoeizfvmbrutpkgnhacjrwld"
   "uqyohizflnbrstpkgnhacjxwld"
   "uquoeizfembrstpkgniacjxwld"
   "uqyoeizfvmbrytpkgnhbcjkwld"
   "pqyoeizfvsbwstpkgnhacjxwld"
   "uqyoerzfvmbrstpkxntacjxwld"
   "uqyoeizfvmbritpkgnhacjqhld"
   "uqyoeisfvmbrstpkglhscjxwld"
   "hqyoeizfvmwrstpwgnhacjxwld"
   "uqyoeyzrvmbrstpkgnhacjxdld"
   "pqyoeozfombrstpkgnhacjxwld"
   "uwyosizfvmbrstpkgnhacjrwld"
   "uqyoegzfvmbrstekbnhacjxwld"
   "uqyoeinfvmirstpkgdhacjxwld"
   "uqyoeizfvmbistpkgnobcjtwld"
   "uqyoeikfvmbrsepkgnhycjxwld"
   "qqyoeiafvmbrstpkgnhacjxold"
   "uqbooizfvmbrstpkgnhacjxwdd"
   "uquoeizfvmbrswpkgnhatjxwld"
   "tqyoejzfvmbrstpkgnhacjxwlv"
   "yqyoeizfvmbrsttkgnhakjxwld"
   "usyoeizfvmbfstpkgnhkcjxwld"
   "gqyocizfvmbrstpkgnhacjbwld"
   "mqyoeizfvmbrstpkgnhacjzzld"
   "uqyoeczfvmbrotpkgnhacjxwsd"
   "jqyoeizfvmkrstpkgnhacaxwld"
   "uqyoeirfvmblstpkgnhaijxwld"
   "uqpoeirfvmbrstpkgbhacjxwld"
   "uqyoiizcvmbrsipkgnhacjxwld"
   "uqyoeizfvmbrstekgnhayjywld"
   "uqyoeizpvmnrstpkgnhacjxwcd"
   "eqyoaizfvmbrstpkgnhacjzwld"
   "uqyubizfvmbrltpkgnhacjxwld"
   "kqmoeizfvmbrstbkgnhacjxwld"
   "uqyoeizfvmkrstpvgnhahjxwld"
   "uqyoeizfrmbrsjpkgchacjxwld"
   "uqyoeizfvmbrstfkgnhacbxwlx"
   "uqyoeizfvmbrstpkbngayjxwld"
   "uqyorizfvmbrstpkgghacjxwle"
   "oqyoeizfvpkrstpkgnhacjxwld"
   "uqyoexzfvmbrscpkgnhacjxwlq"
   "uqkoyilfvmbrstpkgnhacjxwld"
   "uqyotizfamnrstpkgnhacjxwld"
   "uqnoeizfvmbrstpkgnhacdfwld"
   "uqyoeizffmbrstqkgnhacuxwld"
   "uqyoeizfvmbrzhpkgnhqcjxwld"
   "uqyzeizfvmbrsnpkgnracjxwld"
   "jhyoeizfvhbrstpkgnhacjxwld"
   "uqyohizfvmbrstpkgnqhcjxwld"
   "uqyleizfgmbrstlkgnhacjxwld"
   "ucyoeizzvmbrstgkgnhacjxwld"
   "uqyoeizqvmbrstbkgahacjxwld"
   "uqyseizpvkbrstpkgnhacjxwld"
   "uqyobizfvmirstpkgnhachxwld"
   "uqyoiizfvmbrstpkgnhacwxzld"
   "uqyoeizfvmbrstpkgnhafoxsld"
   "pqyoeizfvmbrstpkgnhaijxwle"
   "uqyoeizfvubrstpkgneacjxcld"
   "uqyoeigfumbrstpknnhacjxwld"
   "uqyoeiffvmbrstwkgnhacjxxld"
   "uqooeizfvmbrstpkgnhacjxilv"
   "uqyoeizfvmbrstpkgnhaljirld"
   "uqyoeizfvmbistpkgnoacjtwld"
   "uqyogizfvmlustpkgnhacjxwld"
   "uqyoeizfvmufjtpkgnhacjxwld"
   "uqyoeixfvmbrstpugwhacjxwld"
   "uqyoeizfrzbrsjpkgnhacjxwld"
   "uqyoeizfvmbbsqpkgzhacjxwld"
   "uqyoeizovqfrstpkgnhacjxwld"
   "uqyieizfvmbrsjpkgnhacjxwzd"
   "uqdoeizfvmbrstnkgnqacjxwld"
   "usyoohzfvmbrstpkgnhacjxwld"
   "uqyoeicfvmbrstpkgnhacgxwtd"
   "uqyoeizfvmbrstpkgkhbcjxold"
   "fwyoeizfvmbrstpkgnhkcjxwld"
   "oqyoeizfvmbrstpkenhacjjwld"
   "uqyoeizfvmbrttpkgjhacjhwld"
   "uqyoeituvmbrstpkgohacjxwld"
   "uqyoeizfvekrslpkgnhacjxwld"
   "upyoeizfvmbrstpkgnhjcjxwlb"
   "uqyoeiwfvmbrstpkgshacjmwld"
   "uqyceizfvmbrstpkgnpazjxwld"
   "aqyoeizfvmbrstpkgntacjxwed"
   "uqyosizfvmbrsapkgphacjxwld"
   "uqyoeizfvmbysipkgnhacjxwls"
   "uqyoeicfvmbgstpkgnhacjxwjd"
   "uqyoxizfvmbrsggkgnhacjxwld"
   "uqyoeizfvbbrhtplgnhacjxwld"
   "usyoeizfvmbrstvkgnhacjxwlo"
   "uqyleizfvmbrstpkgnhacjxwac"
   "uqyoeisfvmbrstpfgnhacjxwdd"
   "uqyoeizwvmbvstpkgnhacjxhld"
   "uqyoeczfvmbrstpkgnhecjxwlv"
   "uqyoeizfvmbrstpkgnhacjueid"
   "uqyoeisfvmbrstpkgnhaxjxwzd"
   "uqyoeizfvmbrstpkgnhicjmyld"
   "ugygeizfvmbrmtpkgnhacjxwld"
   "uoyoeiftvmbrstpkgnhacjxwld"
   "uqyoeinfvmbrstpkenhacjxwbd"
   "xqyoeiofvmbrstpkgnhacjxwlt"
   "uqyoeizfvnbrsipkgnhfcjxwld"
   "uqyteizfvmbrstpngmhacjxwld"
   "uqyoeijfvmbrstpdgnhacjcwld"
   "uqyoeizfjmbrstpkgntaclxwld"
   "uqyaeizfvmbrstpkgnhajjxwkd"
   "uqyoeizfvmbraqpkgnhacjxwlv"
   "uqyocizfvmbrstpkqnhrcjxwld"
   "uqyoqizfvmbrdtpkenhacjxwld"
   "uqyoeicfvwbrstpkknhacjxwld"
   "uqyoeizfvmbrstpktnhacjxxlz"
   "uqyoeizfvmbhstpkgnhacjmwgd"
   "uqyoeizfvmorskpkgnhncjxwld"
   "nqyxeezfvmbrstpkgnhacjxwld"
   "uqyoeitfvmbrstpksnhicjxwld"
   "uqyoeizfmmwrstpkgnhacjxwud"
   "uqyoeizfvmmrstpkgnhvcjxwlk"
   "uqyoeizfvmbrstpkgihacjxblz"
   "uqnoeizfvmwrstpkgnhaujxwld"
   "uqyoeizfvlbrsrpkgnhacjxwpd"
   "uqyoeizfvmbwstpkgnhvcjxwdd"
   "uqyoeixfvlbrstpkgxhacjxwld"
   "uqyoeizfvmbjstpmgnhacjxmld"
   "uqyoeizyvhbrstpkgnhacjxwzd"
   "uqyhepzfvmbrstpkghhacjxwld"
   "uqyoetzfvmbrstpkghsacjxwld"
   "uqyoeizfvmbrbnpkgnuacjxwld"
   "uqyokizfvmbrstpkgnhacqiwld"
   "uqyoeizfvmbrstpkgqhacagwld"
   "uqyoeizfvnbvstckgnhacjxwld"
   "uqyoeizfbmbhstpkjnhacjxwld"
   "uqyoeixfvmbrstpkgnegcjxwld"
   "uqyoeizfvmbrstpkshlacjxwld"
   "uqyoeisfhmbrsnpkgnhacjxwld"
   "uqyoekzfvmbrstpkgnhadjxsld"
   "uqyoeizfzmyrstckgnhacjxwld"
   "uqyoeizpvmbrztpkenhacjxwld"
   "uqyopizffmbrstpkgnhacjxuld"
   "uqyoeizfvzhrstpkgnhscjxwld"
   "uqyoeizfvlbrstskvnhacjxwld"
   "uqyohizfvmbrstekgnhacaxwld"
   "uqlodizfvmbastpkgnhacjxwld"
   "uqyoeizfvubrstpbgnhacjvwld"
   "uqnoupzfvmbrstpkgnhacjxwld"
   "tqzoeizfvmbrsdpkgnhacjxwld"
   "pqyobizfvmbrstphgnhacjxwld"
   "uqyweizfvkbrstpkguhacjxwld"
   "uqyoexzfvmbrstzktnhacjxwld"
   "cqyoeizfvmbrstpkgnhacvxfld"
   "uqyoeiefvmbrytpmgnhacjxwld"
   "uqyoeizfvmbhstpkgnhmcjpwld"
   "uqyoeizfvnbrstpkgnhaczrwld"
   "uqyoeibfvnbrstpkgnhacjxvld"
   "uqyoeizfvebrsypygnhacjxwld"
   "uqyoeikfnmbrstukgnhacjxwld"
   "uqyoeizfvmbrsfpkgnhfcdxwld"
   "uqyoeizfvmmrstpnbnhacjxwld"
   "uqyoeizfvmbrztpegnhacjxwrd"
   "pqyoeizfvmbrqtukgnhacjxwld"
   "uqyoeizfvmbbstpkgahacjxpld"
   "uqsoeizfvmbpstpkgnhatjxwld"
   "uqyodizfvmbrsfpkgnhgcjxwld"
   "uuyoeizfvmbnstpkgnhacjxbld"
   "gqyoeizfvmbrstpkgnhacjqwcd"
   "uqyoeizfvmyrotkkgnhacjxwld"
   "uqyoeizfvmabstpkgnhacjawld"
   "uqyoeizfvmbrstpkglhaszxwld"
   "ukyoeizfvmbrstpkgnhacjxtfd"
   "uqeoeizfvmbrstpkgnhtnjxwld"
   "uqyouizfvmnrstpkgxhacjxwld"
   "ugyoeizfvmbrsupygnhacjxwld"])


(assert (not= "uqoeizvmrstpkgnacjxwd" (f2 input)))

(f1 input)
(f2 input)